import type { Resource } from "@/types/entities";
import grainGreen from "@/assets/grain-gradient-green.png";

const now = Date.now();
const daysAgo = (days: number) => new Date(now - days * 24 * 60 * 60 * 1000).toISOString();

const base = {
  isArchived: false,
  archivedAt: null,
  projectIds: [],
};

/** One fixture per each of the 8 reference resources. */
export const resourceFixtures: Resource[] = [
  {
    ...base,
    id: "res-nielsen-norman-onboarding-ux",
    projectIds: ["prj-fintech-onboarding"],
    kind: "link",
    title: "Nielsen Norman — Onboarding UX",
    url: "https://www.nngroup.com/articles/onboarding-ux",
    description: "Research-backed patterns for reducing drop-off in multi-step onboarding.",
    tags: ["UX Research"],
    readingMinutes: 8,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
  {
    ...base,
    id: "res-service-design-doing-ch4",
    kind: "pdf",
    title: "Service Design Doing — ch.4 excerpt",
    url: "https://example.com/service-design-ch4.pdf",
    description: null,
    tags: ["UX Research"],
    filename: "service-design-ch4.pdf",
    pageCount: 18,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(3),
  },
  {
    ...base,
    id: "res-client-brief-fintech",
    projectIds: ["prj-fintech-onboarding"],
    kind: "link",
    title: "Client brief — Fintech app",
    url: "https://notion.so/client-brief-fintech",
    description: "Full project brief, stakeholder list and success metrics.",
    tags: ["Fintech"],
    readingMinutes: null,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(4),
  },
  {
    ...base,
    id: "res-copilot-for-xcode",
    kind: "repo",
    title: "copilot-for-xcode",
    url: "https://github.com/github/CopilotForXcode",
    description: "AI coding assistant for Xcode — reference for inline suggestion UI.",
    tags: ["AI"],
    owner: "github",
    repoName: "copilot-for-xcode",
    language: "Swift",
    stars: 5500,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(3),
  },
  {
    ...base,
    id: "res-w3c-accessible-motion",
    kind: "link",
    title: "W3C — Accessible motion guidelines",
    url: "https://www.w3.org/WAI/accessible-motion",
    description: "Guidance on reduced motion and vestibular-safe animation.",
    tags: ["Accessibility"],
    readingMinutes: 5,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    ...base,
    id: "res-framer-shopify-editions",
    kind: "preview",
    title: "Framer — Shopify Editions Winter '26",
    url: "https://framer.com/shopify-editions-winter-26",
    description: null,
    tags: ["Development"],
    previewImageUrl: grainGreen,
    isFigma: false,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(6),
  },
  {
    ...base,
    id: "res-fintech-component-library",
    kind: "preview",
    title: "Fintech onboarding — component library",
    url: "https://figma.com/fintech-component-library",
    description: null,
    tags: ["Fintech"],
    previewImageUrl: null,
    isFigma: true,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(2),
  },
  {
    ...base,
    id: "res-editorial-type-pairings",
    kind: "link",
    title: "Editorial type pairings",
    url: "https://example.com/editorial-type-pairings",
    description: "Curated serif/sans pairings for editorial products.",
    tags: ["Typography"],
    readingMinutes: 4,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(7),
  },
];
